### ISSUE TITLE
Change API frequently and make break change for developers

### ISSUE THREAD

**Issue by A1Gard** [MHSanaei/3x-ui#451]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hello, 

Thanks for developing this panel.

Panel's API change frequently, It's offensive , when any developers use API need to be stable, but you changing api 3 times since start, and it make break change in our products.

If you want to develop  a professional product you need make  `v1`, `v2` api and etc.

Bug: add client not work at all `404` error, And postman collection not updated too.

Kind regards

### Version of 3x-ui

<details>

```console
v1.4.6
```

**Comment by YasinDehfuli** [comment]
I have this trouble too, plz fix it 🙏

**Comment by ahmadipiralvan** [comment]
Hello
**_addClient_** api has changed to the following address:
host:port/panel/inbound/addClient

@A1Gard @YasinDehfuli

**Comment by A1Gard** [comment]
Thanks

How about break changes of the API's manipulation?
Do you have any idea about version for APIs?

Tell me about approach for API's  future?

**Comment by A1Gard** [comment]
@ahmadipiralvan Problem not solved, and any answer!
Thanks for very very awful support

**Comment by AghaFarokh** [comment]
This is a serious problem
first of all, thank u for developing this project
but changing APIs frequently is causing me some real problems u should add a newer version as a new route and keep the old version API as well
since you are developing this project you are producing bugs as well and bugs are part of any project
we need to keep this app updated to be aware of the bugs but anytime when I update I'm facing some real problems in my app due to changes to the API
It would be nice if keep it simple and professional 
<3
