### ISSUE TITLE
اضافه شدن دامین یا آی‌پی سرو به بک آپ های ارسالی به تلگرام

### ISSUE THREAD

**Issue by elegance666** [MHSanaei/3x-ui#966]
سلام، 
من ۸ تا سرور دارم همه بک آپ ها و اسم دیتابیس یکیه، نمیشه تشخیص داد برای کدوم سرور هستش....

**Comment by wulfric93** [comment]
خب 8 تا ربات باید بالا بیاری

**Comment by ahmadipiralvan** [comment]
Hello
Thank you for your efforts in developing the panel.

**This is an essential requirement for people who have multiple panels.
It would be great if you could add a field to assign a name to each panel and display this name at the top of the panel menu.**

Also, the name of the panel and server IP can be added in the robot reports so that if a robot is used, they can be recognized.

Thank you for everything
